### ISSUE TITLE
How can i submit your code flaw?

### ISSUE THREAD

**Issue by benjioh5** [cVault-finance/CORE-v2#3]
Please just give email and PGP key for submission.

**Comment by 0xRevert** [comment]
Hi,

You can DM me at https://t.me/xRevert
Encrypt your message for 0xd5b47B80668840e7164C1D1d81aF8a9d9727B421

Or PGP
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBF+OVr8BDAC24mfIiAn8iWL0xNUE3E19GAC+pKL9YruTkfCpG3Vax0N3HOj+
lSGRxUSO1FA18oq3FCoT8G/a243Wsv8BfwLVgoc1Ik8HRSQZL9lWw8neYCqdogqd
SvGljujbOX0iVV6Sr7XKFqQe5w1qEhZUI/ssJ4yzwMfQ/Q1CHjr0QKYdzu3zkcIt
tVAboXkh3fSRHxy2woDGDtrHZ3hksupwbyTysPMz1RNVrtkiaeuPwx8eCQqtkyRS
bm3tfb/NKhn85SCzBLgBbOjYO/4YbnaSPvvPh+uy1QWfTQgOMKKW+i/CMDPXxCUW
61uDUKpbCpJ3xzgYQ0a9+xKryjNOGlm/Rl+dWdsNbqHk0jKqJxLfXR4w3uXxhW6Q
SMsF49805BQ0bvL6s5GOvKEfqm+dLvZKSb0zH+MbwZe8y67Ds2/glhMs5M4UGN5B
cGUMFAX8qx1oS00Zxvn+vj3VM1V5HKDx/J1a63t/LvkwDTwaoF52uE0kAuP6/cfl
IwNcSadE76Ni7AsAEQEAAbQfUmV2ZXJ0IDxDb2luUGhEQHByb3Rvbm1haWwuY29t
PokB1AQTAQoAPhYhBIkFK7Fto3DzEO4dgIn6K35k8Bl8BQJfjla/AhsDBQkDwmcA
BQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEIn6K35k8Bl86EML/jXJ7NJmhCNW
aKZJ5GAfATk/dSA8PO9jPYf0INi0HOJmHW6oPf09fU/rac7QaSJmaQouJJciY+F7
e4brE7OAcXtpdTbwxIuKE7UME29ZKs0NUUSrLdpPcDfeR55Wg85nuFQY5IKlKt90
GZEJopbWeClydzUcDISSpTPTO/aO7jy6L8wWqoGBCJEuVHaNfYTPJT42pb//Ws18
pGirRo8gNEHfxOX3wNCS8m6rMvVzFqapQVt6vYK7ZL9F5RdeujAyynZDJtSq88Py
tuXHjeJ0qc7kv84qS2Z8w2VgUBjFK/hK6Q422K94lc7OBPKkX7A+3m4Cqy3IEwpa
cjSzCfJbzMpFzIxfFeVfXdfZ1/cQPIdDWjAhrfEg7r5gAXEllgKgKqH67yO/AViQ
xicEURvbrtbbnESvBJyJJR/faI6M4Vtf6AclEhDasiW5y6QfNFiNH4g+qu0YCadQ
aE+7dMS9Yg7QAfyb55ygkGTC5S/Ed6SWdpFON7Iko3QeYdAuBw0wCLkBjQRfjla/
AQwAyqt+VQfHibxtQ/GqsuUOdL/0a4ZVnDBTVOqliPUs9DDH1n9cHWdz6ohJxeXD
voROYCp+Cnwr9GQ2aAFBB3Vf1IDwb71r0tK0R8u6dalmamEb64DwsCR4W8l7Kuk4
saKaAzkBH8c+jbhik2oTs3vKiSuet8zvvJUA1pMFSY95yiize4s7BUVj3F606spM
xongo4gfQ3s5ex8OwKSmOQixg5LEAAFZjIPEolrLprwY172iDP/bSCBBhrYSqDWu
mq4sXibiwNyr6gMMIDkCIYC6BJglVQuL3fUNGRvWlWgjZLUIAuHv15U6hhsjVivR
u2Mfp/ekwbWkZsAE6JNMudkL+tr69HrV6rgZu9tA6kqNt7W7RlRSZVU6S+yjQYQD
vGYEGThOqspCPhlhIkqn8QMZT9rjrz7dYRxzuujGsll6ljL3kHP5KYLfoBAEHnWS
l1Xfhdr6eOP0uhKXZUajE9lqCpCHdX796L7/Udfhk7gxrG6DtmLXjwUV2jp7f4gR
uAlpABEBAAGJAbwEGAEKACYWIQSJBSuxbaNw8xDuHYCJ+it+ZPAZfAUCX45WvwIb
DAUJA8JnAAAKCRCJ+it+ZPAZfLnFDACPoR71rNTjnFNAEUf+MAaI3vTut+1gLSBm
hL7j0yBEwLzSe5P9Mw0RpWmm7lrCcFI7wdM1YigVtTU3XJgnCz6eqt92ZJ/OhKVG
dnu+G6vBbZD3l4khbgmfM8AKoNdPPSQMH4xx7uMKyOVQlXMuLyhYfpBNt2SkAM/s
e23zQHN4NoF1hTgMg0Flg50qXBkoobH55i4c9jo6hVcpKFwhH2FxgZcGLmLwp/9q
grE+5mrU6/UKmtXSO0Njf0VeqiblqjkNWxv9zpnTcjp4OtPedLU3z2H68Z9xVdJU
eByWD/TmWkfbe7R4Ng/yNWo2m2jHnrS4e5MCridIlyF1AdLfP3pJjQVYd1smV7e8
Mk3biXtNAWJnFGy4aq4UOAs2+pXZlVxfF/n9ChVHoGak6C/OM2b+q720+ExIz2+g
PkWmaVOCHa4Zu+CgJHDAuLXFKyFe5fsIbgl/aTUUyy877aEvgm2ocOMLglp26lCl
the7OrTsKTBWB2zG2eJy37n1+9fLQac=
=Nmx9
-----END PGP PUBLIC KEY BLOCK-----

**Comment by benjioh5** [comment]
thx
